// Audit feature mock data — swap for API responses when the backend is wired up.

export const auditLogs = [
  {
    id: 1,
    avatar: 'https://i.pravatar.cc/64?img=32',
    name: 'Daniel Brooks',
    role: 'Organizer',
    action: 'approved 42 registrations for',
    target: 'Summer Music Festival',
    time: '2 min ago',
    tag: 'Registration',
    tone: 'green',
  },
  {
    id: 2,
    avatar: 'https://i.pravatar.cc/64?img=48',
    name: 'Megan Okafor',
    role: 'Coordinator',
    action: 'submitted a change request for',
    target: 'DevCon Tech Summit',
    time: '18 min ago',
    tag: 'Request',
    tone: 'amber',
  },
  {
    id: 3,
    avatar: 'https://i.pravatar.cc/64?img=25',
    name: 'Priya Nair',
    role: 'Moderator',
    action: 'rejected a late registration for',
    target: 'Art & Design Workshop',
    time: '51 min ago',
    tag: 'Approval',
    tone: 'red',
  },
  {
    id: 4,
    avatar: 'https://i.pravatar.cc/64?img=13',
    name: 'Tom Halvorsen',
    role: 'Organizer',
    action: 'marked',
    target: 'Marathon & Fitness Day',
    suffix: 'as Full',
    time: '1 hr ago',
    tag: 'Registration',
    tone: 'green',
  },
  {
    id: 5,
    avatar: 'https://i.pravatar.cc/64?img=45',
    name: 'Lena Fischer',
    role: 'Coordinator',
    action: 'exported the attendee list for',
    target: 'Annual Gala Dinner',
    time: '2 hrs ago',
    tag: 'Registration',
    tone: 'green',
  },
]
